Document: qontacts
Title: Debian qontacts Manual
Author: <insert document author here>
Abstract: This manual describes what qontacts is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qontacts/qontacts.sgml.gz

Format: postscript
Files: /usr/share/doc/qontacts/qontacts.ps.gz

Format: text
Files: /usr/share/doc/qontacts/qontacts.text.gz

Format: HTML
Index: /usr/share/doc/qontacts/html/index.html
Files: /usr/share/doc/qontacts/html/*.html


